# Copyright (c) 2020 ZMK Firmware Contributors
# Copyright (c) 2020 Endian Technologies AB

# SPDX-License-Identifier: MIT

name: Build and upload PineTime Hypnos

# When to run this Workflow
on: [push]

  # # Run this Workflow when files are pushed to this Branch
  # push:
  #   branches: [ master ]

  # # Also run this Workflow when a Pull Request is created or updated in this Branch
  # pull_request:
  #   branches: [ master ]

# Steps to run for the Workflow
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and upload
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('pinetime/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-init
        with:
          args: 'init "-l pinetime/'
      - name: West Update
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-update
        with:
          args: 'update'
      - name: West Config Zephyr Base
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-config
        with:
          args: 'config "--global zephyr.base-prefer configfile"'
      - name: West Zephyr Export
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-zephyr-export
        with:
          args: 'zephyr-export'
      - name: West Build
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-build
        with:
          args: 'build "-p -b pinetime pinetime/hypnos"'
      # Declare variables
      - name: Declare some variables
        id: vars
        shell: bash
        run:
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      # Upload firmware build
      - name: Upload firmware build
        uses: actions/upload-artifact@v2
        with:
          # Append git hash to file name
          name: hypnos-fw-${{ steps.vars.outputs.sha_short }}
          path: build/zephyr/zephyr.*
